project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: OpenProblemsv1
        menu: 
          - results/index.qmd
          - results/quality_control.qmd
          - href: manuscript/index.qmd
            text: NBT Manuscript
      - text: OpenProblemsv2
        menu: 
          - results_v2/index.qmd
          - results_v2/quality_control.qmd
          - results_v2/migration.qmd
      - text: Documentation
        href: contributing/index.qmd

  sidebar:
    - id: documentation
      collapse-level: 3
      title: Documentation
      contents: 
        - contributing/index.qmd
        - "contributing/quick_start.qmd"
        - "contributing/requirements.qmd"
        - text: Extend a task
          href: contributing/extend_task/index.qmd
          contents:
            - href: contributing/extend_task/index.qmd
              text: Overview
            - auto: contributing/extend_task/*.qmd
        - text: Create a new task
          href: contributing/create_task/index.qmd
          contents:
            - href: contributing/create_task/index.qmd
              text: Overview
            - auto: contributing/create_task/*.qmd
        - "contributing/code_of_conduct.qmd"
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute:
  freeze: auto