project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  site-url: https://openproblems-experimental.netlify.com
  repo-url: https://github.com/openproblems-bio/website-experimental
  repo-actions: [edit, issue] 
  
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: OpenProblemsv1
        href: results/index.qmd
      - text: OpenProblemsv2
        href: results_v2/index.qmd
      - href: team/index.qmd
        text: Team
      - text: Documentation
        href: contributing/index.qmd

  sidebar:
    - id: documentation
      collapse-level: 3
      title: Documentation
      contents: 
        - contributing/index.qmd
        - "contributing/quick_start.qmd"
        - "contributing/requirements.qmd"
        - text: Analyse results
          href: contributing/analyse_results/index.qmd
        - text: Run a method
          href: contributing/run_method/index.qmd
        - text: Extend a task
          href: contributing/extend_task/index.qmd
          contents:
            - href: contributing/extend_task/index.qmd
              text: Overview
            - auto: contributing/extend_task/*.qmd
        - text: Create a new task
          href: contributing/create_task/index.qmd
          contents:
            - href: contributing/create_task/index.qmd
              text: Overview
            - auto: contributing/create_task/*.qmd
        - "contributing/code_of_conduct.qmd"
    - id: results_v1
      title: OpenProblemsv1
      href: results/index.qmd
      contents:
        - text: Overview
          href: results/index.qmd
        - section: Results
          contents: 
            - auto: results/*/index.qmd
        - results/quality_control.qmd
        - text: NBT Manuscript
          href: manuscript/index.qmd
    - id: results_v2
      title: OpenProblemsv2
      href: results_v2/index.qmd
      contents:
        - text: Overview
          href: results_v2/index.qmd
        - text: Denoising
          contents: 
            - href: results_v2/denoising/index.qmd
              text: Description
            - results_v2/denoising/methods.qmd
            - results_v2/denoising/metrics.qmd
            - results_v2/denoising/api.qmd
            - results_v2/denoising/normalization.qmd
        - text: Label projection
          contents: 
            - href: results_v2/label_projection/index.qmd
              text: Description
            - results_v2/label_projection/methods.qmd
            - results_v2/label_projection/metrics.qmd
            - results_v2/label_projection/api.qmd
            - results_v2/label_projection/normalization.qmd
        - results_v2/quality_control.qmd
        - results_v2/migration.qmd
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute:
  freeze: auto