project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  site-url: https://openproblems-experimental.netlify.com
  repo-url: https://github.com/openproblems-bio/website-experimental
  repo-actions: [edit, issue] 


  page-footer:
    left: "© Open Problems 2022 · View on [GitHub](https://github.com/openproblems-bio/openproblems). Made with [Quarto♥](https://quarto.org)."
  
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: Benchmarks
        href: results/index.qmd
      - text: Benchmarks v2
        href: results_v2/index.qmd
      - href: team/index.qmd
        text: Team
      - text: Documentation
        href: contributing/index.qmd

  sidebar:
    - id: documentation
      collapse-level: 3
      title: Documentation
      contents: 
        - documentation/index.qmd
        - "documentation/quick_start.qmd"
        - "documentation/requirements.qmd"
        - text: Analyse results
          href: documentation/analyse_results/index.qmd
        - text: Run a method
          href: documentation/run_method/index.qmd
        - text: Extend a task
          href: documentation/extend_task/index.qmd
          contents:
            - href: documentation/extend_task/index.qmd
              text: Overview
            - auto: documentation/extend_task/*.qmd
        - text: Create a new task
          href: documentation/create_task/index.qmd
          contents:
            - href: documentation/create_task/index.qmd
              text: Overview
            - auto: contributing/create_task/*.qmd
        - "contributing/code_of_conduct.qmd"
    - id: results_v2
      title: OpenProblemsv2
      href: results_v2/index.qmd
      contents:
        - text: Overview
          href: results_v2/index.qmd
        - text: Denoising
          contents: 
            - href: results_v2/denoising/index.qmd
              text: Description
            - results_v2/denoising/methods.qmd
            - results_v2/denoising/metrics.qmd
            - results_v2/denoising/api.qmd
            - results_v2/denoising/normalization.qmd
        - text: Dimensionality reduction
          contents: 
            - href: results_v2/dimensionality_reduction/index.qmd
              text: Description
            - results_v2/dimensionality_reduction/methods.qmd
            - results_v2/dimensionality_reduction/metrics.qmd
            - results_v2/dimensionality_reduction/api.qmd
            - results_v2/dimensionality_reduction/normalization.qmd
        - text: Label projection
          contents: 
            - href: results_v2/label_projection/index.qmd
              text: Description
            - results_v2/label_projection/methods.qmd
            - results_v2/label_projection/metrics.qmd
            - results_v2/label_projection/api.qmd
            - results_v2/label_projection/normalization.qmd
        - results_v2/quality_control.qmd
        - results_v2/migration.qmd
format:
  html:
    theme: [ simplex, theme.scss ]
    css: styles.css
    toc: true

execute:
  freeze: auto