project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  description: Open Problems in Single Cell Analysis
  favicon: images/icon.png
  site-url: https://openproblems-experimental.netlify.com
  repo-url: https://github.com/openproblems-bio/website-experimental
  repo-actions: [edit, issue] 

  page-footer:
    left: "© Open Problems 2022 · View on [GitHub](https://github.com/openproblems-bio/openproblems). Made with [Quarto♥](https://quarto.org)."
  
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: Benchmarks
        href: results/index.qmd
      - text: Benchmarks v2
        href: results_v2/index.qmd
      - text: Competitions
        menu: 
          - text: NeurIPS 2022
            href: competitions/neurips_2022
          - text: NeurIPS 2021
            href: competitions/neurips_2021
          - text: NeurIPS 2021 docs
            href: competitions/neurips_2021_docs
      - href: team/index.qmd
        text: Team
      - text: Documentation
        href: documentation/index.qmd

  sidebar:
    - id: documentation
      collapse-level: 3
      title: Documentation
      contents:
        - documentation/analyse_results/index.qmd
        - documentation/execute/index.qmd
        - documentation/first_setup/index.qmd
        - documentation/contribute/index.qmd
        - documentation/development/index.qmd
        - documentation/code_of_conduct.qmd
    - id: neurips2021_docs
      title: NeurIPS2021
      contents: 
        - competitions/neurips_2021_docs/index.qmd
        - text: General
          href: competitions/neurips_2021_docs/about/index.qmd
          contents: competitions/neurips_2021_docs/about/*
        - text: Data
          href: competitions/neurips_2021_docs/data/index.qmd
          contents: competitions/neurips_2021_docs/data/*
        - text: The tasks
          href: competitions/neurips_2021_docs/about_tasks/index.qmd
          contents: competitions/neurips_2021_docs/about_tasks/*
        - text: Submissions
          href: competitions/neurips_2021_docs/submission/index.qmd
          contents: competitions/neurips_2021_docs/submission/*
format:
  html:
    # theme:
    #   light: [ simplex, theme.scss ]
    #   dark: [ darkly, theme.scss ]
    theme: [ simplex, theme.scss ]
    css: styles.css
    toc: true

execute:
  freeze: auto