project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - results/index.qmd
      - href: manuscript/index.qmd
        text: Manuscript

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute:
  freeze: auto