project:
  type: website
  preview:
    port: 4200

website:
  title: "OpenProblems"
  navbar:
    logo: images/logo.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: OpenProblemsv1
        menu: 
          - results/index.qmd
          - results/quality_control.qmd
          - href: manuscript/index.qmd
            text: NBT Manuscript
      - text: OpenProblemsv2
        menu: 
          - results_v2/index.qmd
          - results_v2/quality_control.qmd
          - results_v2/migration.qmd
      - text: Documentation
        href: contributing/index.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

execute:
  freeze: auto