name: base_r
description: An R2U 22.04 image with anndata preinstalled.
engines:
  - type: docker
    image: rocker/r2u:22.04
    setup:
      - type: apt
        packages:
          - git
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        packages:
          - rpy2
          - anndata~=0.10.0
          - scanpy~=1.10.0
          - pyyaml
          - requests
          - jsonschema
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
      - type: r
        packages:
          - anndata
          - BiocManager
          - reticulate
          - bit64
        github:
          - openproblems-bio/core/packages/r/openproblems
