#' Process a viash config file
#'
#' This function will process a viash config file in the following ways:
#'
#' * Upgrade the config from viash < 0.9 to viash >= 0.9 format.
#' * Add 'full_name' field to the config, which is the namespace/name of the config.
#' * Add 'all_arguments' field to the config, which is a flattened list of all arguments
#'   in the config, with an additional 'clean_name' field that is the argument name without
#'   any leading dashes.
#'
#' @param target_config_path Path to a Viash config file in the target directory.
#'   Example: `target/executable/path/to/.config.vsh.yaml`.
#' @param project_root_dir Path to the root of the Viash project. If not provided,
#'   it will be determined automatically based on the target config path.
#'
#' @return The processed config as a named list.
#'
#' @importFrom fs path_rel path
#'
#' @export
read_viash_config <- function(
    target_config_path,
    project_root_dir = find_project_root(target_config_path)) {
  # note: if this config was not generated by viash, use `viash config view` first?
  config <- read_nested_yaml(target_config_path)

  rel_target_config_path <- fs::path_rel(target_config_path, project_root_dir)

  # upgrade config from viash < 0.9 to viash >= 0.9 format
  if (!is.null(config$functionality)) {
    # rename info to build_info
    config$build_info <- config$info
    config$info <- NULL

    # if there is build info, fix it
    if (!is.null(config$build_info)) {
      # determine what the project directory was during build time
      rel_config_dir <- dirname(rel_target_config_path)
      abs_build_dir <- gsub(paste0("/", rel_config_dir), "", config$build_info$output)

      # get platform types
      platform_types <- sapply(config$platforms, function(platform) platform$type)

      # fix build_info
      config$build_info$config <-
        fs::path_rel(config$build_info$config, abs_build_dir)
      config$build_info$output <-
        fs::path_rel(config$build_info$output, abs_build_dir)
      config$build_info$executable <-
        if (config$build_info$platform == "nextflow") {
          fs::path(config$build_info$output, "main.nf")
        } else {
          fs::path_rel(config$build_info$executable, abs_build_dir)
        }
      config$build_info$runner <-
        if (config$build_info$platform == "nextflow") {
          "nextflow"
        } else {
          "executable"
        }
      config$build_info$engine <-
        if (config$build_info$platform == "nextflow") {
          "docker|native"
        } else {
          paste(
            platform_types[platform_types %in% c("docker", "native")],
            collapse = "|"
          )
        }
    }

    # move functionality to top level
    config[names(config$functionality)] <- config$functionality
    config$functionality <- NULL

    # might need to parse argument groups
    if (!is.null(config$arguments)) {
      arg_group <- list(
        name = "Arguments",
        arguments = config$arguments
      )
      # check whether there is already an argument group named 'Arguments'
      existing_ix <- which(sapply(
        config$argument_groups,
        function(grp) grp$name == "Arguments"
      ))
      # if so, merge the arguments
      if (length(existing_ix) > 0) {
        arg_group$arguments <- c(
          config$argument_groups[[existing_ix]]$arguments,
          arg_group$arguments
        )
        config$argument_groups[[existing_ix]] <- arg_group
      } else {
        config$argument_groups <- c(config$argument_groups, list(arg_group))
      }
    }
  }

  # add helper fields
  config$full_name <-
    if (is.null(config$namespace)) {
      config$name
    } else {
      paste0(config$namespace, "/", config$name)
    }

  # add a flattened list of arguments
  # also add a clean_name field to each argument
  all_arguments <- list()
  for (arg_group in config$argument_groups) {
    grp_args <- lapply(arg_group$arguments, function(argument) {
      argument$clean_name <- gsub("^-*", "", argument$name)
      argument
    })
    all_arguments <- c(all_arguments, grp_args)
  }
  config$all_arguments <- all_arguments

  # return the processed config
  config
}
