name: extract_uns_metadata
namespace: h5ad
description: Extract .uns metadata from an h5ad file and write it to a yaml file.
argument_groups:
  - name:  Inputs
    arguments:
      - name: --input
        type: file
        required: true
        description: A h5ad file.
      - name: --schema
        type: file
        required: false
        description: An optional schema with which to annotate the output
  - name: Output
    arguments:
      - name: --output
        type: file
        required: true
        description: A yaml file containing the metadata.
        example: output_meta.yaml
        direction: output
resources:
  - type: python_script
    path: script.py
test_resources:
  - path: /resources_test/common/pancreas
  - type: python_script
    path: test.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    test_setup:
      - type: python
        packages: viashpy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
