#' Render the README.qmd file for a task
#'
#' @param task_metadata Task metadata as returned by `read_task_metadata`
#' @param add_instructions Add instructions to the README.qmd
#'
#' @return A qmd documentation string
#'
#' @export
#'
#' @examples
#' path <- system.file("extdata", "example_project", package = "openproblems.docs")
#'
#' task_metadata <- read_task_metadata(path)
#'
#' render_task_readme_qmd(task_metadata)
render_task_readme_qmd <- function(task_metadata, add_instructions = FALSE) {
  cli::cli_inform("Render authors")
  authors_str <- .render_task_authors(task_metadata)

  cli::cli_inform("Render task graph")
  task_graph <- .render_task_graph(task_metadata)

  cli::cli_inform("Render task API parts")
  task_api_parts <- .render_task_parts(task_metadata)

  cli::cli_inform("Determine repository URL")
  repository_url <- task_metadata$proj_conf$links$repository
  regex <- "https://github.com/([^/]+/[^/]+)"
  repository_name <- stringr::str_match(repository_url, regex)[, 2]

  instructions <-
    if (add_instructions) {
      cli::cli_inform("Render help string")
      .render_instructions(task_metadata)
    } else {
      ""
    }

  cli::cli_inform("Render README.qmd")
  strip_margin(glue("
    |---
    |title: \"{task_metadata$proj_conf$label}\"
    |format: gfm
    |---
    |
    |<!--
    |This file is automatically generated from the tasks's api/*.yaml files.
    |Do not edit this file directly.
    |-->
    |
    |{task_metadata$proj_conf$summary}
    |
    |Repository: [{repository_name}]({repository_url})
    |
    |{instructions}
    |
    |## Description
    |
    |{task_metadata$proj_conf$description}
    |
    |{authors_str}
    |
    |## API
    |
    |{task_graph}
    |
    |{paste(task_api_parts, collapse = '\n\n')}
    |"))
}

#' @importFrom openproblems.utils list_as_data_frame
.render_task_authors <- function(task_metadata) {
  authors <- task_metadata$proj_conf$authors

  if (length(authors) == 0) {
    return("")
  }

  authors_df <- map_dfr(authors, function(aut) {
    aut$roles <- paste(aut$roles, collapse = ", ")
    list_as_data_frame(aut)
  })

  paste0(
    "\n## Authors & contributors\n\n",
    authors_df |> knitr::kable() |> paste(collapse = "\n"),
    "\n"
  )
}

.render_task_graph <- function(task_metadata) {
  graph <- task_metadata$task_graph
  order <- task_metadata$task_graph_order

  vdf <- igraph::as_data_frame(graph, "vertices") |>
    arrange(match(.data$name, order))
  edf <- igraph::as_data_frame(graph, "edges") |>
    arrange(match(.data$from, order), match(.data$to, order))

  strip_margin(glue("
    |```mermaid
    |flowchart LR
    |{paste(vdf$str, collapse = '\n')}
    |{paste(edf$str, collapse = '\n')}
    |```
    |"), symbol = "\\|")
}

.render_task_parts <- function(task_metadata) {
  order <- task_metadata$task_graph_order

  map_chr(
    order,
    function(file_name) {
      if (!is.null(task_metadata$comps[[file_name]])) {
        render_component_spec(task_metadata$comps[[file_name]])
      } else {
        render_file_format(task_metadata$files[[file_name]])
      }
    }
  )
}

.render_instructions <- function(task_metadata) {
  proj_name <- task_metadata$proj_conf$name

  # TODO: this needs to be streamlined

  strip_margin(glue("
    |### Installation
    |
    |You need to have Docker, Java, and Viash installed. Follow
    |[these instructions](https://openproblems.bio/documentation/fundamentals/requirements)
    |to install the required dependencies.
    |
    |### Add a method
    |
    |To add a method to the repository, follow the instructions in the `scripts/add_a_method.sh` script.
    |
    |### Initial setup
    |
    |To get started, you can run the following commands:
    |
    |```bash
    |git clone git@github.com:openproblems-bio/{proj_name}.git
    |
    |cd {proj_name}
    |
    |# initialise submodule
    |scripts/init_submodule.sh
    |
    |# download resources
    |scripts/download_resources.sh
    |```
    |
    |To run the benchmark, you first need to build the components. Afterwards, you can run the benchmark:
    |
    |```bash
    |viash ns build --parallel --setup cachedbuild
    |
    |scripts/run_benchmark.sh
    |```
    |
    |After adding a component, it is recommended to run the tests to ensure that the component is working correctly:
    |
    |```bash
    |viash ns test --parallel
    |```
    |
    |Optionally, you can provide the `--query` argument to test only a subset of components:
    |
    |```bash
    |viash ns test --parallel --query 'component_name'
    |```
    |"))
}
